### ISSUE TITLE
compileJava NO-SOURSE

### ISSUE THREAD

**Issue by ivanyangtt** [DiUS/pact-workshop-jvm#1]
when i did command in step 1: ./gradlew :consumer:run ,i got a problem like this 

$ ./gradlew :consumer:run
:consumer:compileJava NO-SOURCE
:consumer:compileGroovy UP-TO-DATE
:consumer:processResources NO-SOURCE
:consumer:classes UP-TO-DATE
:consumer:run
Exception in thread "main" groovy.lang.GroovyRuntimeException: Could not find matching constructor for: au.com.dius.pactworkshop.consumer.Client(java.lang.String)
        at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1732)
        at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1532)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
        at au.com.dius.pactworkshop.consumer.Consumer.run(Consumer.groovy:5)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:925)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:908)
        at org.codehaus.groovy.runtime.InvokerHelper.runScript(InvokerHelper.java:412)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
        at au.com.dius.pactworkshop.consumer.Consumer.main(Consumer.groovy)
:consumer:run FAILED

**Comment by uglyog** [comment]
What git branch where you on when you ran it? master?

**Comment by ivanyangtt** [comment]
i am on master, need i checkout step n branch when i perform the step n？

**Comment by uglyog** [comment]
There is a stepn branch for each step, but master should be the same as step13. Can you try again? There has been a number of changes since your issue was raised.

**Comment by ivanyangtt** [comment]
Thank you for the answer, I have completed all the steps. I am very interested in this test method, I hope this method will be integrated into the swagger, when users use codegen generated code can contain pact test method, Do you have any suggestions?

**Comment by uglyog** [comment]
It is difficult to integrate with swagger, because Pact enables specification by example, while swagger is specification by API path. 

However, Atlassian has a tool that can verify that a pact file and swagger specification match. See https://bitbucket.org/atlassian/swagger-request-validator

**Comment by andrewowen** [comment]
this is still an issue as of right now...I think it is because of the way the providers are newly structured?

**Comment by andrewowen** [comment]
```
 pact-workshop-jvm step1 ✓ ./gradlew :consumer:run
:consumer:compileJava NO-SOURCE
:consumer:compileGroovy
:consumer:processResources NO-SOURCE
:consumer:classes
:consumer:run
```

This is what I get

**Comment by uglyog** [comment]
That seems to be working, I'm not sure what the issue is?
