### ISSUE TITLE
Step2 giving error, not working as explained

### ISSUE THREAD

**Issue by safiuz** [DiUS/pact-workshop-jvm#11]
After checking out of step2(i.e. git checkout step2) I'm giving command on consumer window: ./gradlew :consumer:run
its giving below **error** :  
`
> Task :consumer:run FAILED
Exception in thread "main" com.mashape.unirest.http.exceptions.UnirestException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8080 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
        at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
        at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)
        at au.com.dius.pactworkshop.consumer.Client.loadProviderJson(Client.java:17)
        at au.com.dius.pactworkshop.consumer.Client.fetchAndProcessData(Client.java:21)
        at au.com.dius.pactworkshop.consumer.Consumer.main(Consumer.java:7)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8080 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
        at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)

`
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':consumer:run'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
2 actionable tasks: 1 executed, 1 up-to-date

**_Not able to figure out whats going wrong.
I have stopped the dropwizard-provider that was running in the first terminal after performing step1._**

**Comment by pkubowicz** [comment]
I suppose you mean the instruction
>  Running the actual client against any of the providers results in a runtime exception!

Setting up Dropwizard provider with `./gradlew :providers:dropwizard-provider:run` as described in step 1 works for me when I check out step 2.
